#ifndef HAL_PINMUX_H
#define HAL_PINMUX_H

#include "gd32e23x.h"
#define HAL_LED_RED_PORT GPIOB
#define HAL_LED_RED_PIN GPIO_PIN_8
#define HAL_LED_GREEN_PORT GPIOB
#define HAL_LED_GREEN_PIN GPIO_PIN_9
#define HAL_LED_BLUE_PORT GPIOF
#define HAL_LED_BLUE_PIN GPIO_PIN_6
#define HAL_LED_WHITE_PORT GPIOF
#define HAL_LED_WHITE_PIN GPIO_PIN_7

#define HAL_EN_1V8_PORT GPIOB
#define HAL_EN_1V8_PIN GPIO_PIN_10
#define HAL_TR_SWITCH_PORT GPIOB
#define HAL_TR_SWITCH_PIN GPIO_PIN_12
#define HAL_POGO_IN_PORT GPIOB
#define HAL_POGO_IN_PIN GPIO_PIN_13
#define HAL_SHIP_CTRL_PORT GPIOB
#define HAL_SHIP_CTRL_PIN GPIO_PIN_14
#define HAL_RPD_PORT GPIOB
#define HAL_RPD_PIN GPIO_PIN_15
#define HAL_PDET_EN_PORT GPIOB
#define HAL_PDET_EN_PIN GPIO_PIN_1
#define HAL_KEY5353_PORT GPIOA
#define HAL_KEY5353_PIN GPIO_PIN_15

#define HAL_POGO3V3_EN_PORT GPIOB
#define HAL_POGO3V3_EN_PIN GPIO_PIN_11
#define HAL_BOOST_5V_EN_PORT GPIOB
#define HAL_BOOST_5V_EN_PIN GPIO_PIN_5

#define HAL_BAT_PMOS_EN_PORT GPIOC
#define HAL_BAT_PMOS_EN_PIN GPIO_PIN_13

#define HAL_BAT_INT_PORT GPIOA
#define HAL_BAT_INT_PIN GPIO_PIN_8
#define HAL_NINT_PORT GPIOA
#define HAL_NINT_PIN GPIO_PIN_7
#define HAL_CHARGER_INT_PORT GPIOB
#define HAL_CHARGER_INT_PIN GPIO_PIN_2
#define HAL_PDETB_PORT GPIOB
#define HAL_PDETB_PIN GPIO_PIN_0

#define HAL_KEY_PORT GPIOB
#define HAL_KEY_PIN GPIO_PIN_3
#define HAL_HALL_PORT GPIOB
#define HAL_HALL_PIN GPIO_PIN_4

#define HAL_I2C_SCL_PORT GPIOB
#define HAL_I2C_SCL_PIN GPIO_PIN_6
#define HAL_I2C_SDA_PORT GPIOB
#define HAL_I2C_SDA_PIN GPIO_PIN_7

#define HAL_UART_TX_PORT GPIOA
#define HAL_UART_TX_PIN GPIO_PIN_9
#define HAL_UART_RX_PORT GPIOA
#define HAL_UART_RX_PIN GPIO_PIN_10

typedef enum
{
    HAL_PIN_LED_RED,
    HAL_PIN_LED_GREEN,
    HAL_PIN_LED_BLUE,
    HAL_PIN_LED_WHITE,
    HAL_PIN_EN_1V8,
    HAL_PIN_TR_SWITCH,
    HAL_PIN_POGO_IN,
    HAL_PIN_SHIP_CTRL,
    HAL_PIN_RPD,
    HAL_PIN_PDET_EN,
    HAL_PIN_KEY5353,
    HAL_PIN_POGO3V3_EN,
    HAL_PIN_BOOST_5V_EN,
    HAL_PIN_BAT_INT,
    HAL_PIN_NINT,
    HAL_PIN_CHARGER_INT,
    HAL_PIN_PDETB,
    HAL_PIN_KEY,
    HAL_PIN_HALL,
    HAL_PIN_I2C_SCL,
    HAL_PIN_I2C_SDA,
    HAL_PIN_UART_TX,
    HAL_PIN_UART_RX,
    HAL_PIN_COUNT
} hal_pin_t;

#endif
